# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cluster_brown <- function(text_file, output_dir, min_occur = 5L, initC = 100L, ncollocs = 500L, plen = 1L, num_threads = 1L, chk = FALSE, print_stats = FALSE, paths2map = FALSE) {
    .Call('_brown_cluster_brown', PACKAGE = 'brown', text_file, output_dir, min_occur, initC, ncollocs, plen, num_threads, chk, print_stats, paths2map)
}

